language: node_js
node_js: 8.11.1
services: mongodb

cache:
  directories:
    - /home/travis/build/RoySegall/bonappetit/server/node_modules
    - /home/travis/build/RoySegall/bonappetit/front/node_modules

before_script:
  # Setting up server.
  - cd server
  - npm i -g tslint typescript ts-node
  - npm i -D jest typescript
  - npm i -D ts-jest @types/jest
  - cp .env.travis .env
  - cd -

  # Setting up front server.
  - cd front
  - npm i
  - npm run test-coverage
  - npm run lint

script:
  # Testing the server.
  - cd server
  - npm run lint
  - npm run unit-test

  # TBD: Testing the front
