language: node_js
node_js: 8.11.1
services: mongodb

cache:
  directories:
    - /home/travis/build/RoySegall/bonappetit/server/node_modules
    - /home/travis/build/RoySegall/bonappetit/front/node_modules

env:
  matrix:
    - SECTION=front
    - SECTION=server
    - SECTION=both


before_script:
  - bash trvis/before_$SECTION.sh

script:
  - bash trvis/run_$SECTION.sh
